language: python
python:
  - "2.7"

before_script:
  - mysql -u root < ./tests/mysql-provision.sql

# command to install dependencies
install:
  - pip install mysql-connector-python==1.1.6 --upgrade --allow-external

# command to run tests
script: python setup.py test