language: python
python:
  - "2.7"

before_script:
  - mysql -u root < ./tests/mysql-provision.sql

# command to install dependencies
install:
  - pip install --allow-external -r ./tests/requirements.txt

# command to run tests
script: python setup.py test